FROM mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019 AS windows-base

SHELL ["powershell", "-NoProfile", "-ExecutionPolicy", "Bypass", "-Command"]

RUN Set-ExecutionPolicy Bypass -Scope Process -Force; \
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; \
    iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1')); \
    $env:PATH = 'C:\ProgramData\chocolatey\bin;' + $env:PATH; \
    [Environment]::SetEnvironmentVariable('PATH', $env:PATH, [EnvironmentVariableTarget]::Machine)

RUN choco install -y git cmake ninja python3 unzip curl 7zip --no-progress

RUN Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/vs_buildtools.exe" -OutFile "$env:TEMP\vs_buildtools.exe"; \
    Start-Process -Wait -FilePath "$env:TEMP\vs_buildtools.exe" -ArgumentList \
    '--quiet --wait --norestart --nocache \
     --add Microsoft.VisualStudio.Workload.VCTools \
     --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 \
     --add Microsoft.VisualStudio.Component.VC.ATL \
     --add Microsoft.VisualStudio.Component.VC.ATLMFC \
     --add Microsoft.VisualStudio.Component.VC.Redist.14.Latest \
     --add Microsoft.VisualStudio.Component.Windows10SDK.19041 \
     --add Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Core \
     --add Microsoft.VisualStudio.Component.TextTemplating \
     --add Microsoft.VisualStudio.Component.VC.CoreIde \
     --add Microsoft.VisualStudio.Component.VC.CMake.Project \
     --add Microsoft.VisualStudio.Component.Windows11SDK.22000'; \
    Remove-Item -Force "$env:TEMP\vs_buildtools.exe"

RUN git clone --depth=1 -b stable https://github.com/flutter/flutter.git C:\flutter

RUN $env:PATH = 'C:\flutter\bin;C:\flutter\bin\cache\dart-sdk\bin;C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin;' + $env:PATH; \
    [Environment]::SetEnvironmentVariable('PATH', $env:PATH, [EnvironmentVariableTarget]::Machine)

RUN git config --global --add safe.directory C:/flutter

RUN flutter config --enable-windows-desktop --no-analytics

RUN flutter doctor -v

FROM windows-base AS windows-build

WORKDIR C:/voosu

COPY . .

RUN flutter pub get

RUN if (!(Test-Path -Path 'out')) { mkdir out }

CMD powershell -NoProfile -Command \
    "Write-Host '==> Building Windows'; \
    flutter doctor -v; \
    flutter build windows --release; \
    Copy-Item -Path 'build\windows\x64\runner\Release\*' -Destination 'C:\voosu\out' -Recurse -Force;"